server:
  port: 8989
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: NEVER
    include-exception: false
spring:
  application:
    name: aarogyaniketan
  datasource:
    url: jdbc:postgresql://localhost:5432/cmt
    username: postgres
    pasword: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect