server:
  port: 8989
spring:
  application:
    name: aarogyaniketan
  datasource:
    url: jdbc:postgresql://localhost:5432/cmt
    username: postgres
    pasword: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect